# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/57/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/57/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mgh/Desktop/Travel_Agency

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mgh/Desktop/Travel_Agency

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/57/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/57/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgh/Desktop/Travel_Agency/CMakeFiles /home/mgh/Desktop/Travel_Agency/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mgh/Desktop/Travel_Agency/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Travel_Agency

# Build rule for target.
Travel_Agency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Travel_Agency
.PHONY : Travel_Agency

# fast build rule for target.
Travel_Agency/fast:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/build
.PHONY : Travel_Agency/fast

Admin/admin.o: Admin/admin.cpp.o

.PHONY : Admin/admin.o

# target to build an object file
Admin/admin.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Admin/admin.cpp.o
.PHONY : Admin/admin.cpp.o

Admin/admin.i: Admin/admin.cpp.i

.PHONY : Admin/admin.i

# target to preprocess a source file
Admin/admin.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Admin/admin.cpp.i
.PHONY : Admin/admin.cpp.i

Admin/admin.s: Admin/admin.cpp.s

.PHONY : Admin/admin.s

# target to generate assembly for a file
Admin/admin.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Admin/admin.cpp.s
.PHONY : Admin/admin.cpp.s

BankAccounts/bankaccounts.o: BankAccounts/bankaccounts.cpp.o

.PHONY : BankAccounts/bankaccounts.o

# target to build an object file
BankAccounts/bankaccounts.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/BankAccounts/bankaccounts.cpp.o
.PHONY : BankAccounts/bankaccounts.cpp.o

BankAccounts/bankaccounts.i: BankAccounts/bankaccounts.cpp.i

.PHONY : BankAccounts/bankaccounts.i

# target to preprocess a source file
BankAccounts/bankaccounts.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/BankAccounts/bankaccounts.cpp.i
.PHONY : BankAccounts/bankaccounts.cpp.i

BankAccounts/bankaccounts.s: BankAccounts/bankaccounts.cpp.s

.PHONY : BankAccounts/bankaccounts.s

# target to generate assembly for a file
BankAccounts/bankaccounts.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/BankAccounts/bankaccounts.cpp.s
.PHONY : BankAccounts/bankaccounts.cpp.s

Cities/cities.o: Cities/cities.cpp.o

.PHONY : Cities/cities.o

# target to build an object file
Cities/cities.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Cities/cities.cpp.o
.PHONY : Cities/cities.cpp.o

Cities/cities.i: Cities/cities.cpp.i

.PHONY : Cities/cities.i

# target to preprocess a source file
Cities/cities.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Cities/cities.cpp.i
.PHONY : Cities/cities.cpp.i

Cities/cities.s: Cities/cities.cpp.s

.PHONY : Cities/cities.s

# target to generate assembly for a file
Cities/cities.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Cities/cities.cpp.s
.PHONY : Cities/cities.cpp.s

Discounts/discount.o: Discounts/discount.cpp.o

.PHONY : Discounts/discount.o

# target to build an object file
Discounts/discount.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Discounts/discount.cpp.o
.PHONY : Discounts/discount.cpp.o

Discounts/discount.i: Discounts/discount.cpp.i

.PHONY : Discounts/discount.i

# target to preprocess a source file
Discounts/discount.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Discounts/discount.cpp.i
.PHONY : Discounts/discount.cpp.i

Discounts/discount.s: Discounts/discount.cpp.s

.PHONY : Discounts/discount.s

# target to generate assembly for a file
Discounts/discount.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Discounts/discount.cpp.s
.PHONY : Discounts/discount.cpp.s

Drivers/drivers.o: Drivers/drivers.cpp.o

.PHONY : Drivers/drivers.o

# target to build an object file
Drivers/drivers.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Drivers/drivers.cpp.o
.PHONY : Drivers/drivers.cpp.o

Drivers/drivers.i: Drivers/drivers.cpp.i

.PHONY : Drivers/drivers.i

# target to preprocess a source file
Drivers/drivers.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Drivers/drivers.cpp.i
.PHONY : Drivers/drivers.cpp.i

Drivers/drivers.s: Drivers/drivers.cpp.s

.PHONY : Drivers/drivers.s

# target to generate assembly for a file
Drivers/drivers.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Drivers/drivers.cpp.s
.PHONY : Drivers/drivers.cpp.s

Users/tickets.o: Users/tickets.cpp.o

.PHONY : Users/tickets.o

# target to build an object file
Users/tickets.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/tickets.cpp.o
.PHONY : Users/tickets.cpp.o

Users/tickets.i: Users/tickets.cpp.i

.PHONY : Users/tickets.i

# target to preprocess a source file
Users/tickets.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/tickets.cpp.i
.PHONY : Users/tickets.cpp.i

Users/tickets.s: Users/tickets.cpp.s

.PHONY : Users/tickets.s

# target to generate assembly for a file
Users/tickets.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/tickets.cpp.s
.PHONY : Users/tickets.cpp.s

Users/users.o: Users/users.cpp.o

.PHONY : Users/users.o

# target to build an object file
Users/users.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/users.cpp.o
.PHONY : Users/users.cpp.o

Users/users.i: Users/users.cpp.i

.PHONY : Users/users.i

# target to preprocess a source file
Users/users.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/users.cpp.i
.PHONY : Users/users.cpp.i

Users/users.s: Users/users.cpp.s

.PHONY : Users/users.s

# target to generate assembly for a file
Users/users.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/Users/users.cpp.s
.PHONY : Users/users.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Travel_Agency.dir/build.make CMakeFiles/Travel_Agency.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Travel_Agency"
	@echo "... edit_cache"
	@echo "... Admin/admin.o"
	@echo "... Admin/admin.i"
	@echo "... Admin/admin.s"
	@echo "... BankAccounts/bankaccounts.o"
	@echo "... BankAccounts/bankaccounts.i"
	@echo "... BankAccounts/bankaccounts.s"
	@echo "... Cities/cities.o"
	@echo "... Cities/cities.i"
	@echo "... Cities/cities.s"
	@echo "... Discounts/discount.o"
	@echo "... Discounts/discount.i"
	@echo "... Discounts/discount.s"
	@echo "... Drivers/drivers.o"
	@echo "... Drivers/drivers.i"
	@echo "... Drivers/drivers.s"
	@echo "... Users/tickets.o"
	@echo "... Users/tickets.i"
	@echo "... Users/tickets.s"
	@echo "... Users/users.o"
	@echo "... Users/users.i"
	@echo "... Users/users.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

